# This file was generated by liblab | https://liblab.com/

from gitguardian import Gitguardian, Environment

sdk = Gitguardian(access_token="YOUR_ACCESS_TOKEN", base_url=Environment.DEFAULT.value)

result = sdk.api_tokens.self_retrieve_api_token()

print(result)
